trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pool:
  name: 'vh-self-hosted'

variables:
  buildConfiguration: 'Release'
  artifactName: $(Build.BuildId)-AutomationTests

stages:
- stage: Build
  displayName: CI Build
  jobs:
  - job: CI_Build
    displayName: CI Build
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: $(artifactName)

- stage: Automation_Test
  pool:
    name: windows-latest
  displayName: Automation Test
  jobs:
  - job: Automation_Test
    displayName: Automation Test
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download Pipeline Artifacts
        inputs:
          artifactName: $(artifactName)
          targetPath: $(Pipeline.Workspace)/AutomationTests
      - task: VSTest@2
        displayName: Run Tests
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(Pipeline.Workspace)/AutomationTests/UI/**'
          resultsFolder: '$(Agent.TempDirectory)/TestResultsUI'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '$(Agent.TempDirectory)/*.xml'
