
trigger: 
- master
- fix_for_issue_with_app_settings_config

pr:
- master

pool:
  name: 'vh-self-hosted'

variables:
- group: vh-automation-test

stages:
- stage: Automation_Tests
  jobs:
  - job: Automation_Tests
    steps:
    - bash: |
       echo $APP_SETTINGS > "$(System.DefaultWorkingDirectory)/API/RestSharpAPI/appSettings.json"
       cat "$(System.DefaultWorkingDirectory)/API/RestSharpAPI/appSettings.json"
       echo $APP_SETTINGS > "$(System.DefaultWorkingDirectory)/UI/Selenium/appSettings.json"
       cat "$(System.DefaultWorkingDirectory)/UI/Selenium/appSettings.json"
      displayName: Transform App Settings
      env:
        APP_SETTINGS: $(app_settings)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: PublishTestResults@2
      condition: succeededOrFailed()

