
trigger: none

pr: none

parameters:
- name: runUITests
  displayName: Run UI Tests
  type: boolean
  default: true

- name: runApiTests
  displayName: Run API Tests
  type: boolean
  default: false

- name: environment
  type: string
  default: Dev
  values:
    - Dev
    - Test
    - Stg
    - Prod

pool:
  name: 'VH Self Hosted'

stages:

####################################################
# UI Testing. ######################################
- stage: Automation_Tests_${{ parameters.environment }}
  displayName: Automation Tests ${{ parameters.environment }}
  jobs:
  - ${{ if eq(parameters.runUITests, true) }}:
    - job: UI_Tests
      displayName: UI Tests ${{ parameters.environment }}
      variables:
      - name: env
        value: ${{ lower(replace(parameters.environment, 'stg', 'staging')) }}
      - name: projectPath
        value: "UI/Selenium"
      - group: vh-automation-test-${{ parameters.environment }}
      steps:

      - task: FileTransform@1
        displayName: Transform App Settings
        inputs:
          folderPath: $(projectPath)
          fileType: json
          targetFiles: appsettings.json

      - pwsh: |
          Get-Content "$(projectPath)/appsettings.json"
        displayName: Print App Settings

      - task: DotNetCoreCLI@2
        displayName:  Run UI Tests
        inputs:
          command: build
          projects: '$(projectPath)/*.csproj'
          arguments: '--configuration Release'
          publishTestResults: true

      # - task: DotNetCoreCLI@2
      #   displayName:  Build UI Tests
      #   inputs:
      #     command: 'build'
      #     projects: '$(projectPath)/*.csproj'
      #     arguments: '--configuration Release'
      
      - task: VisualStudioTestPlatformInstaller@1
        displayName: Run VS Test Installer
        inputs:
          packageFeedSelector: 'nugetOrg'
          versionSelector: 'latestStable'

      - task: VSTest@2
        displayName:  Run UI Tests
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\UISelenium.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          rerunFailedTests: true
          rerunMaxAttempts: '2'
          publishRunAttachments: True