trigger: none

pr: none

parameters:
  - name: environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
      - Stg

name: ${{ parameters.environment }}_UI_Regression_Tests_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: "VH Self Hosted"

stages:
  ####################################################
  # UI Testing. ######################################
  - stage: Automation_Tests_${{ parameters.environment }}
    displayName: Automation Tests ${{ parameters.environment }}
    jobs:
      - job: UI_Tests
        displayName: UI Tests ${{ parameters.environment }}
        variables:
          - template: variables/${{ lower(parameters.environment) }}.yaml
          - template: variables/shared.yaml
            parameters:
              environment: ${{ parameters.environment }}
          - group: vh-automation-test-${{ parameters.environment }}
          - group: Saucelabs
          - group: KinlyConfiguration_${{ parameters.environment }}
          - name: ApiClientConfiguration.BookingsApi.Url
            value: ${{ variables.bookingsApiUrl }}
          - name: TestDataConfiguration.AudioLinkCaseNumber
            value: ${{ variables.audioLinkCaseNumber }}

        steps:
          - template: pipelines/templates/run-ui-test.yaml
            parameters:
              environment: ${{ parameters.environment }}
              projectPath: ${{ variables.projectPath }}
              testRunTitle: "UI Tests ${{ parameters.environment }}"
              subscriptionName: ${{ variables.subscriptionName }}
