trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*
    - FinalPipeline

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  artifactName: $(Build.BuildId)-AutomationTests

stages:
- stage: Build
  displayName: CI Build
  jobs:
  - job: CI_Build
    displayName: CI Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        publishTestResults: true
        projects: '**/*.csproj'
