trigger: none

pr: none

schedules:
  - cron: "15 9 * * *"
    displayName: Daily build
    always: true
    branches:
      include:
        - master

parameters:
  - name: runUITests
    displayName: Run UI Tests
    type: boolean
    default: true

  - name: runA11yTests
    displayName: Run Accessibiliy Tests
    type: boolean
    default: true

  - name: environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
      - Stg

name: ${{ parameters.environment }}_UI_Daily_Tests_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: "VH Self Hosted"

stages:
  ####################################################
  # UI Testing. ######################################
  - stage: Automation_Tests_${{ parameters.environment }}
    displayName: Automation Tests ${{ parameters.environment }}
    jobs:
      - ${{ if eq(parameters.runUITests, true) }}:
          - job: UI_Tests
            displayName: UI Tests ${{ parameters.environment }}
            variables:
              - template: variables/${{ lower(parameters.environment) }}.yaml
              - template: variables/shared.yaml
                parameters:
                  environment: ${{ parameters.environment }}
              - group: vh-automation-test-${{ parameters.environment }}
              - group: Saucelabs
              - group: KinlyConfiguration_${{ parameters.environment }}
              - name: ApiClientConfiguration.BookingsApiUrl
                value: ${{ variables.bookingsApiUrl }}
              - name: ApiClientConfiguration.VideoApiUrl
                value: ${{ variables.videoApiUrl }}
              - name: TestDataConfiguration.AudioLinkCaseNumber
                value: ${{ variables.audioLinkCaseNumber }}
              - group: slack

            steps:
              - template: pipelines/templates/run-ui-test.yaml
                parameters:
                  environment: ${{ parameters.environment }}
                  projectPath: ${{ variables.projectPath }}
                  testCategory: Daily
                  testRunTitle: "UI Tests ${{ parameters.environment }}"
                  subscriptionName: ${{ variables.subscriptionName }}
              
              - task: PublishBuildArtifacts@1
                displayName: Publish UI Test Output
                condition: succeededOrFailed()
                inputs:
                  pathToPublish: "$(Agent.TempDirectory)/"
                  artifactName: UI_Report
              
              - template: pipelines/templates/get-results-from-trx.yaml
                parameters:
                    name: UI

              - template: pipelines/templates/send-results-to-slack.yaml
                parameters:
                  results: $(testSummary)
                  triggerID: $(triggerID)
                  type: UI Tests


      - ${{ if eq(parameters.runA11yTests, true) }}:
          - job: A11Y_Tests
            displayName: A11Y Tests ${{ parameters.environment }}
            variables:
              - template: variables/${{ lower(parameters.environment) }}.yaml
              - template: variables/shared.yaml
                parameters:
                  environment: ${{ parameters.environment }}
              - group: vh-automation-test-${{ parameters.environment }}
              - group: Saucelabs
              - group: KinlyConfiguration_${{ parameters.environment }}
              - name: SystemConfiguration.EnvironmentConfigSettings.RunOnSauceLabs
                value: true
              - name: SystemConfiguration.EnvironmentConfigSettings.EnableAccessibilityCheck
                value: true
              - name: SystemConfiguration.EnvironmentConfigSettings.AccessibilityReportFilePath
                value: $(Build.ArtifactStagingDirectory)/axe-results.json
              - name: SystemConfiguration.EnvironmentConfigSettings.AccessibilityHtmlReportFilePath
                value: $(Build.ArtifactStagingDirectory)/axe-results.html
              - name: ApiClientConfiguration.BookingsApiUrl
                value: ${{ variables.bookingsApiUrl }}
              - name: ApiClientConfiguration.VideoApiUrl
                value: ${{ variables.videoApiUrl }}
              - group: slack

            steps:
              - template: pipelines/templates/run-ui-test.yaml
                parameters:
                  environment: ${{ parameters.environment }}
                  projectPath: ${{ variables.projectPath }}
                  testCategory: a11y
                  testRunTitle: "UI Tests ${{ parameters.environment }}"
                  subscriptionName: ${{ variables.subscriptionName }}

              - task: PublishBuildArtifacts@1
                displayName: Publish A11Y Output
                condition: succeededOrFailed()
                inputs:
                  pathToPublish: "$(Agent.TempDirectory)/"
                  artifactName: A11Y_Report

              - template: pipelines/templates/get-results-from-trx.yaml
                parameters:
                    name: A11y
                  
              - template: pipelines/templates/send-results-to-slack.yaml
                parameters:
                  results: $(testSummary)
                  triggerID: $(triggerID)
                  type: A11y Tests