trigger: 
- VIH-9112-v2

pr:
- master

parameters:
- name: runUITests
  displayName: Run UI Tests
  type: boolean
  default: true

- name: environment
  type: string
  default: Preview
  values:
    - Preview
    - Dev
    - AAT
    - Sandbox
    - Test1
    - Test2
    - Demo
    - Preprod
    - Prod


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Package

  jobs: 
    - job: Publish_Automation_Tests
      variables:
      - name: projectPath
        value: "UI/Selenium"

      steps: 
        - checkout: self

        - task: DotNetCoreCLI@2 
          displayName: dotnet Restore
          inputs: 
            command: restore
            projects: '$(projectPath)/*.csproj'
        
        - task: DotNetCoreCLI@2
          displayName: donet Publish
          inputs: 
            command: publish
            publishWebProjects: false
            arguments: --configuration Release --no-restore --output $(build.artifactstagingdirectory)/AutomationTests
            zipAfterPublish: false
            workingDirectory: $(projectPath)

        - task: PublishBuildArtifacts@1
          displayName: Publish AutomationTests
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)/AutomationTests
            ArtifactName: AutomationTests

- stage: Run_Tests

  jobs: 
    - deployment: Yada
      strategy: 
        runOnce: 
          deploy: 
            steps:  
              - checkout: none

              - download: none

              - task: DownloadPipelineArtifact@2
                displayName: Download App Binaries
                inputs:
                  artifact: App
                  path: $(Pipeline.Workspace)/App
                  preferTriggeringPipeline: true
                  source: current


# ####################################################
# # UI Testing. ######################################
# - stage: Automation_Tests_${{ parameters.environment }}
#   displayName: Automation Tests ${{ parameters.environment }}
#   jobs:
#   - ${{ if eq(parameters.runUITests, true) }}:
#     - job: UI_Tests
#       displayName: UI Tests ${{ parameters.environment }}
#       variables:
#       - name: env
#         value: ${{ lower(replace(parameters.environment, 'stg', 'staging')) }}
#       - name: projectPath
#         value: "UI/Selenium"
#       steps:

#       - task: DotNetCoreCLI@2
#         displayName: Restore
#         inputs:
#           command: restore
#           projects: '$(projectPath)/*.csproj'

#       - task: FileTransform@1
#         displayName: Transform App Settings
#         inputs:
#           folderPath: $(projectPath)
#           fileType: json
#           targetFiles: appsettings.json

#       - bash: | 
#           mv appsettings.json appsettings.old.json
#           mv appsettings.json appsettings.json
#           echo "##[section]Printing appsettings.json ..."
#           cat appsettings.json
#         displayName: Move App Settings
#         workingDirectory: $(projectPath)

#       - task: DotNetCoreCLI@2
#         displayName:  Run UI Tests
#         inputs:
#           command: test
#           projects: '$(projectPath)/*.csproj'
#           arguments: '--configuration Release -l "console;verbosity=detailed"'

#       - task: DotNetCoreCLI@2
#         displayName: donet Publish
#         inputs:
#           command: publish
#           publishWebProjects: false
#           arguments: --configuration Release --output $(build.artifactstagingdirectory)/AcceptanceTests
#           zipAfterPublish: false
#           workingDirectory: ${{ parameters.coreProjectPath }}.AcceptanceTests
#         condition: eq(variables.NUGET_CACHE_RESTORED, 'true')

#       - task: PublishBuildArtifacts@1
#         displayName: Publish AcceptanceTests
#         inputs:
#           PathtoPublish: $(Build.ArtifactStagingDirectory)/AcceptanceTests
#           ArtifactName: AcceptanceTests

#       - task: PublishTestResults@2
#         condition: succeededOrFailed()