trigger: none
pr: none

schedules:
  - cron: '0 19 * * 1,2,3,4,5'
    displayName: Daily build
    always: true
    branches:
      include:
        - master

parameters:
  - name: runUITests
    displayName: Run UI Tests
    type: boolean
    default: true

  - name: runA11yTests
    displayName: Run Accessibility Tests
    type: boolean
    default: true

  - name: runOnSaucelabs
    displayName: Run on SauceLabs
    type: boolean
    default: true

  - name: runHeadlessBrowser
    displayName: Run Headless Browser (Required for PR environments)
    type: boolean
    default: false

  - name: adminWebOverrideUrl
    displayName: Admin Web URL Override
    type: string
    default: ' ' # Optional parameter with default value

  - name: videoWebOverrideUrl
    displayName: Video Web URL Override
    type: string
    default: ' ' # Optional parameter with default value

  - name: environment
    displayName: Environment name (used by to get the correct configuration from LaunchDarkly and KeyVault)
    type: string
    default: Dev
    values:
      - Dev
      - Demo
      - Test
      - Stg

  - name: testCategories
    type: object
    default:
      - admin
      - video

name: ${{ parameters.environment }}_UI_Daily_Tests_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: 'VH Self Hosted'

stages:
  ####################################################
  # UI Testing. ######################################
  - stage: Automation_Tests_${{ parameters.environment }}
    displayName: Automation Tests ${{ parameters.environment }}
    jobs:
      - ${{ if eq(parameters.runUITests, true) }}:
          - ${{ each testCategory in parameters.testCategories }}:
              - job: UI_Tests_${{ testCategory }}
                cancelTimeoutInMinutes: 80
                displayName: UI Tests ${{ parameters.environment }} - ${{ testCategory }}
                variables:
                  - name: SystemConfiguration.EnvironmentConfigSettings.EnableAccessibilityCheck
                    value: false
                  - template: variables/${{ lower(parameters.environment) }}.yaml
                  - template: variables/shared.yaml
                    parameters:
                      environment: ${{ parameters.environment }}
                      runOnSauceLabs: ${{ parameters.runOnSaucelabs }}
                      runHeadlessBrowser: ${{ parameters.runHeadlessBrowser }}
                      adminWebOverrideUrl: ${{ parameters.adminWebOverrideUrl }}
                      videoWebOverrideUrl: ${{ parameters.videoWebOverrideUrl }}
                  - group: vh-automation-test-${{ parameters.environment }}
                  - group: FeatureFlags_${{ parameters.environment }}
                  - group: Saucelabs
                  - group: KinlyConfiguration_${{ parameters.environment }}
                  - name: ApiClientConfiguration.BookingsApiUrl
                    value: ${{ variables.bookingsApiUrl }}
                  - name: ApiClientConfiguration.VideoApiUrl
                    value: ${{ variables.videoApiUrl }}
                  - name: ApiClientConfiguration.UserApiUrl
                    value: ${{ variables.userApiUrl }}
                  - group: slack

                steps:
                  - template: pipelines/templates/run-ui-test.yaml
                    parameters:
                      environment: ${{ parameters.environment }}
                      projectPath: ${{ variables.projectPath }}
                      testRunTitle: 'UI Tests ${{ parameters.environment }} - ${{ testCategory }}'
                      testCategory: ${{ testCategory }}
                      subscriptionName: ${{ variables.subscriptionName }}

                  - task: PublishBuildArtifacts@1
                    displayName: Publish UI Test Output
                    condition: succeededOrFailed()
                    inputs:
                      pathToPublish: '$(Agent.TempDirectory)/'
                      artifactName: UI_Report

                  - task: PublishBuildArtifacts@1
                    displayName: Publish UI HTML Report
                    condition: succeededOrFailed()
                    inputs:
                      pathToPublish: '$(Build.ArtifactStagingDirectory)/UITestReports/'
                      artifactName: UI_Html_Report

                  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:
                      - template: pipelines/templates/get-results-from-trx.yaml
                        parameters:
                          name: UI

                      - template: pipelines/templates/send-results-to-slack.yaml
                        parameters:
                          env: ${{ parameters.environment }}
                          results: $(testOutcome)
                          details: $(testSummary)
                          triggerID: $(triggerID)
                          type: UI Tests - ${{ testCategory }}

      - ${{ if eq(parameters.runA11yTests, true) }}:
          - job: A11Y_Tests
            displayName: A11Y Tests ${{ parameters.environment }}
            variables:
              - template: variables/${{ lower(parameters.environment) }}.yaml
              - template: variables/shared.yaml
                parameters:
                  environment: ${{ parameters.environment }}
                  runOnSauceLabs: ${{ parameters.runOnSaucelabs }}
                  adminWebOverrideUrl: ${{ parameters.adminWebOverrideUrl }}
                  videoWebOverrideUrl: ${{ parameters.videoWebOverrideUrl }}
              - group: vh-automation-test-${{ parameters.environment }}
              - group: Saucelabs
              - group: FeatureFlags_${{ parameters.environment }}
              - group: KinlyConfiguration_${{ parameters.environment }}
              - name: SystemConfiguration.EnvironmentConfigSettings.EnableAccessibilityCheck
                value: true
              - name: SystemConfiguration.EnvironmentConfigSettings.AccessibilityReportFilePath
                value: $(Build.ArtifactStagingDirectory)/axe-results.json
              - name: SystemConfiguration.EnvironmentConfigSettings.AccessibilityHtmlReportFilePath
                value: $(Build.ArtifactStagingDirectory)/axe-results.html
              - name: ApiClientConfiguration.BookingsApiUrl
                value: ${{ variables.bookingsApiUrl }}
              - name: ApiClientConfiguration.VideoApiUrl
                value: ${{ variables.videoApiUrl }}
              - name: ApiClientConfiguration.UserApiUrl
                value: ${{ variables.userApiUrl }}
              - group: slack

            steps:
              - template: pipelines/templates/run-ui-test.yaml
                parameters:
                  environment: ${{ parameters.environment }}
                  projectPath: ${{ variables.projectPath }}
                  testCategory: a11y
                  testRunTitle: 'UI Tests ${{ parameters.environment }}'
                  subscriptionName: ${{ variables.subscriptionName }}
                  netVersion: 8.x

              - task: PublishBuildArtifacts@1
                displayName: Publish A11Y Output
                condition: succeededOrFailed()
                inputs:
                  pathToPublish: '$(Build.ArtifactStagingDirectory)/'
                  artifactName: A11Y_Report

              - task: PublishBuildArtifacts@1
                displayName: Publish A11Y Output
                condition: succeededOrFailed()
                inputs:
                  pathToPublish: '$(Agent.TempDirectory)/'
                  artifactName: A11Y_Report_Temp

              - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:
                  - template: pipelines/templates/get-results-from-trx.yaml
                    parameters:
                      name: A11y

                  - template: pipelines/templates/send-results-to-slack.yaml
                    parameters:
                      env: ${{ parameters.environment }}
                      results: $(testOutcome)
                      details: $(testSummary)
                      triggerID: $(triggerID)
                      type: A11y Tests
