
trigger: 
- master

pr:
- master

pool:
  name: 'vh-self-hosted'

stages:
- stage: Automation_Tests
  jobs:
  - job: Automation_Tests
    steps:
    - bash: |
       echo $APP_SETTINGS > "$(System.DefaultWorkingDirectory)/API/RestSharpAPI/appSettings.json"
       cat "$(System.DefaultWorkingDirectory)/API/RestSharpAPI/appSettings.json"
       echo $APP_SETTINGS > "$(System.DefaultWorkingDirectory)/UI/Selenium/appSettings.json"
       cat "$(System.DefaultWorkingDirectory)/UI/Selenium/appSettings.json"
      displayName: Transform App Settings
      env:
        APP_SETTINGS: $(app_settings)

- stage: Build
  displayName: CI Build
  jobs:
  - job: CI_Build
    displayName: CI Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

- stage:
  displayName: Test
  jobs:
  - job: Run_Test
    steps:
    - task: DotNetCoreCLI@2
      inputs:
       command: 'run'
       projects: '**/*.csproj'
       arguments: '--configuration $(buildConfiguration)'

- stage:
  displayName: PublishTests
  jobs:
  - job: Publish_Tests
    steps:
    - task: PublishTestResults@2
      inputs:
       testResultsFormat: 'VSTest'
       testResultsFiles: '**/TEST-*.xml'