
trigger: 
- master

pr:
- master

parameters:
- name: runUITests
  type: boolean
  default: true

- name: runApiTests
  type: boolean
  default: false

- name: environment
  type: string
  default: Dev
  values:
    - Dev
    - Demo
    - Stg
    - Prod

pool:
  name: 'vh-self-hosted'

variables:
- group: vh-automation-test

stages:


- stage: Automation_Tests_${{ parameters.environment }}
  displayName: Automation Tests ${{ parameters.environment }}
  jobs:
  - ${{ if eq(parameters.runUITests, true) }}:
    - job: UI_Tests
      displayName: UI Tests ${{ parameters.environment }}
      variables:
      - name: projectPath
        value: "UI/Selenium"
      steps:

      - task: FileTransform@1
        displayName: Transform App Settings
        inputs:
          folderPath: $(projectPath)
          fileType: json
          targetFiles: appSettings.sds.json

      - bash: | 
          mv appSettings.json appSettings.old.json
          mv appSettings.sds.json appSettings.json
        displayName: Move App Settings
        workingDirectory: $(projectPath)

      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: '$(projectPath)/*.csproj'
          arguments: '--configuration Release'

      - task: PublishTestResults@2
        condition: succeededOrFailed()