
trigger: none

pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily midnight build
    always: true
    branches:
      include:
        - master

parameters:
- name: runUITests
  displayName: Run UI Tests
  type: boolean
  default: true

- name: runApiTests
  displayName: Run API Tests
  type: boolean
  default: false

- name: environment
  type: string
  default: Dev
  values:
    - Dev
    - Test
    - Stg
    - Prod

pool:
  name: 'VH Self Hosted'

stages:

####################################################
# UI Testing. ######################################
- stage: Automation_Tests_${{ parameters.environment }}
  displayName: Automation Tests ${{ parameters.environment }}
  jobs:
  - ${{ if eq(parameters.runUITests, true) }}:
    - job: UI_Tests
      displayName: UI Tests ${{ parameters.environment }}
      variables:
      - name: env
        value: ${{ lower(replace(parameters.environment, 'stg', 'staging')) }}
      - name: projectPath
        value: "UI/Selenium"
      - group: vh-automation-test-${{ parameters.environment }}
      steps:

      - task: FileTransform@1
        displayName: Transform App Settings
        inputs:
          folderPath: $(projectPath)
          fileType: json
          targetFiles: appsettings.json

      - task: DotNetCoreCLI@2
        displayName:  Run UI Tests
        inputs:
          command: test
          projects: '$(projectPath)/*.csproj'
          arguments: '--configuration Release'
          publishTestResults: true