trigger: none
pr: none

schedules:
  - cron: '0 18 * * 1,2,3,4,5'
    displayName: Daily build
    always: true
    branches:
      include:
        - master

parameters:
  - name: runUITests
    displayName: Run UI Tests
    type: boolean
    default: true

  - name: runA11yTests
    displayName: Run Accessibility Tests
    type: boolean
    default: true

  - name: runOnSaucelabs
    displayName: Run on SauceLabs
    type: boolean
    default: true

  - name: runHeadlessBrowser
    displayName: Run Headless Browser (Required for PR environments)
    type: boolean
    default: false

  - name: adminWebOverrideUrl
    displayName: Admin Web URL Override (leave blank for default)
    type: string
    default: ' ' # Optional parameter with default value

  - name: videoWebOverrideUrl
    displayName: Video Web URL Override (leave blank for default)
    type: string
    default: ' ' # Optional parameter with default value

  - name: bookingsApiOverrideUrl
    displayName: Bookings API PR Url (leave blank for default)
    type: string
    default: ' '
  - name: videoApiOverrideUrl
    displayName: Video API PR Url (leave blank for default)
    type: string
    default: ' '
  - name: userApiOverrideUrl
    displayName: User API PR Url (leave blank for default)
    type: string
    default: ' '

  - name: environment
    displayName: Environment name (used by to get the correct configuration from LaunchDarkly and KeyVault)
    type: string
    default: Dev
    values:
      - Dev
      - Demo
      - Test
      - Stg

  - name: testCategories
    type: object
    default:
      - admin
      - video

name: ${{ parameters.environment }}_UI_Daily_Tests_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: 'VH Self Hosted'

jobs:
  - template: pipelines/templates/pipeline.yaml
    parameters:
      environment: ${{ parameters.environment }}
      runUITests: ${{ parameters.runUITests }}
      runA11yTests: ${{ parameters.runA11yTests }}
      runOnSaucelabs: ${{ parameters.runOnSaucelabs }}
      runHeadlessBrowser: ${{ parameters.runHeadlessBrowser }}
      adminWebOverrideUrl: ${{ parameters.adminWebOverrideUrl }}
      videoWebOverrideUrl: ${{ parameters.videoWebOverrideUrl }}
      bookingsApiOverrideUrl: ${{ parameters.bookingsApiOverrideUrl }}
      videoApiOverrideUrl: ${{ parameters.videoApiOverrideUrl }}
      userApiOverrideUrl: ${{ parameters.userApiOverrideUrl }}
      testCategories: ${{ parameters.testCategories }}
